class User:
    """User class to store information about a specific user playing the game."""

    def __init__(self, locksport=''):
        self.guesses = []
        self.guess_values = {
            'sum': 0,
            'product': 1
        }
        self.score = 0
        self.attempts_remaining = 3

    def guess_code(self):
        """Takes three inputs to guess the random code generated by the engine."""
        guesses = []
        x = 0
        while x < 3:
            prompt = ""
            if x == 0:
                prompt = "Guess the first number: "
            if x == 1:
                prompt = "Guess the second number: "
            if x == 2:
                prompt = "Guess the third number: "
            guess = input(prompt)
            if guess.isdigit():
                guesses.append(int(guess))
                x += 1
        self.guesses = guesses